### PR TITLE
Update to 5.12 and latest KDE platform

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
testbot, build

**Comment by nedrichards** [comment]
testbot, build

**Comment by nedrichards** [comment]
Audio playback is broken:
```
(ktuberling:3): GLib-GObject-CRITICAL **: 08:33:03.578: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_object_ref: assertion 'object != NULL' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_bin_add_many: assertion 'GST_IS_ELEMENT (element_1)' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_element_link_pads_full: assertion 'GST_IS_ELEMENT (src)' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_element_get_static_pad: assertion 'GST_IS_ELEMENT (element)' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_ghost_pad_new: assertion 'GST_IS_PAD (target)' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_element_add_pad: assertion 'GST_IS_PAD (pad)' failed

(ktuberling:3): GStreamer-CRITICAL **: 08:33:03.579: gst_object_unref: assertion 'object != NULL' failed
```

**Comment by tsdgeos** [comment]
Wow my flatpak is asserting with those instructions

$ flatpak install --user https://dl.flathub.org/build-repo/98/org.kde.ktuberling.flatpakref
**
flatpak:ERROR:app/flatpak-main.c:700:flatpak_run: assertion failed: (success || error)

Any idea why? Any other way to test it?

**Comment by nedrichards** [comment]
I think it's because i built this seconds before the 'test' build system got deployed to the real new build system. https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/ new features are awesome though! will build again.

**Comment by nedrichards** [comment]
bot, build

**Comment by tsdgeos** [comment]
Seems to me gstreamer is wrongly built in in the 18.08 base (that is what sdk 5.12 uses compared to 1.6 used in 5.11)

@jjardon do you know who could help debug that?

According to strace the plugins are looked for at /usr/lib/gstreamer-1.0 but they live at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/

**Comment by jjardon** [comment]
The plugins being in /usr/lib/x86_64-linux-gnu/gstreamer-1.0/ is expected

Check https://gitlab.gnome.org/GNOME/gnome-build-meta/commit/e669996d8c79f64b98cea0695cb06afabb516c92 for a fix for the GNOME runtime

**Comment by alatiera** [comment]
This was reported in the fd.o-sdk bug tracker as well, but its a bug in the KDE runtime where it overwrites the `GST_PLUGIN_SYSTEM_PATH` to a non existing place. I suggest you wait till this is fixed in the KDE runtime.

[Issue](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/622#note_141004868)

**Comment by jjardon** [comment]
@alatiera Is there an issue open against the KDE runtime somewhere? I will try to send a patch if nobody beat me to it

**Comment by tsdgeos** [comment]
Ok, should be fixed by https://phabricator.kde.org/D19175 (92.15% sure)

**Pull request merged**
